version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: asd123



  elasticsearch:
     image: elasticsearch:7.17.10
     ports:
       - 9200:9200
       - 9300:9300
     environment:
        discovery.type: single-node

    ## docker-compose.yml dosyasının bulunduğu dizin de aşağıdaki komutu çalıştrırsak docker-compose.yml dosyasında yazılı olan komutlar çalışmaya başlayacaktır.
    ##docker-compose -f docker-compose.yml up -d